In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('bikroy_2026-08-25.csv')

In [4]:
df.head()

,raw_title,price,condition_raw,location,posted_date,url,photo_count,scraped_at,seller_type,description
0,Apple iPhone 15 256 GB Blue,85000,Used,"Chattogram, CDA Avenue",05/08,https://bikroy.com/cda-avenue/mobile-phones/ap...,3,2026-08-25T14:45:10.274203+00:00,individual,"The phone was used only for taking pictures, o..."
1,Samsung Galaxy S25 FE 128 GB Blue,49999,Used,"Dhaka, Khilgaon",3 hours ago,https://bikroy.com/khilgaon/mobile-phones/sams...,5,2026-08-25T14:45:12.268350+00:00,individual,Price Fixed.\nThe phone has not been opened or...
2,Samsung Galaxy A17 5G 128 GB Black,24000,Used,"Chattogram, Chandgaon",18/08,https://bikroy.com/chandgaon/mobile-phones/sam...,4,2026-08-25T14:45:14.125232+00:00,individual,Samsung Galaxy A17 comes with a box and a free...
3,Samsung Galaxy S21 5G 128 GB White,18000,Used,"Rajshahi, Shaheb Bazar",04/08,https://bikroy.com/shaheb-bazar/mobile-phones/...,4,2026-08-25T14:45:15.640807+00:00,individual,Display changed \nDisplay has slight scratches...
4,Xiaomi Redmi Turbo 4 Pro 256 GB Black,35500,Used,"Dhaka, Uttara",6 hours ago,https://bikroy.com/uttara/mobile-phones/xiaomi...,3,2026-08-25T14:45:17.606774+00:00,individual,"Redmi Turbo 4 Pro, all okay, fully fresh."

In [5]:
df.shape

(552, 10)

In [6]:
df.tail()

,raw_title,price,condition_raw,location,posted_date,url,photo_count,scraped_at,seller_type,description
547,New Xiaomi Redmi Note 14 Pro 256 GB,20000,Brand New,"Chattogram, Patenga",21/08,https://bikroy.com/patenga/mobile-phones/new-x...,3,2026-08-25T14:51:14.153267+00:00,individual,"No problem in the mobile, selling it for money"
548,Xiaomi Poco X6 Pro 256 GB Black,24500,Used,"Chattogram, Muradpur",8 hours ago,https://bikroy.com/muradpur/mobile-phones/xiao...,3,2026-08-25T14:51:14.443802+00:00,individual,Poco X6 Pro 5G\n 8GB RAM / 256GB Storage\n Ful...
549,Xiaomi Redmi Note 13 Pro+ 256 GB,26000,Used,"Chattogram, Hathazari",20/08,https://bikroy.com/hathazari/mobile-phones/xia...,5,2026-08-25T14:51:15.177522+00:00,individual,The phone is in completely fresh condition.\nL...
550,New Xiaomi Redmi Note 13 Pro 512 GB White,28999,Brand New,"Chattogram, Agrabad",12 hours ago,https://bikroy.com/agrabad/mobile-phones/new-x...,2,2026-08-25T14:51:15.603738+00:00,individual,Call or message us on WhatsApp at our number p...
551,New Xiaomi 15 Pro 256 GB Black,32000,Brand New,"Chattogram, Mirsharai",19/08,https://bikroy.com/mirsharai/mobile-phones/new...,4,2026-08-25T14:51:16.162964+00:00,individual,Brought from Dubai. Never used.

In [8]:
df.shape

(552, 10)