In [17]:
import pandas as pd

In [19]:
df = pd.read_csv('bikroy_2026-08-27.csv')

In [22]:
df.head()

,raw_title,price,condition_raw,location,posted_date,url,photo_count,scraped_at,seller_type,description
0,Apple iPhone 14 Pro Max 256 GB Black,58000,Used,"Chattogram, Halishahar",12/08,https://bikroy.com/halishahar/mobile-phones/ap...,5,2026-08-27T07:27:44.691612+00:00,individual,Sell post \nIPHONE 14 PRO MAX \n256 gb \nBH- 8...
1,Apple iPhone 16 Pro Max 256 GB White,118000,Used,"Rajshahi, Shaheb Bazar",2 hours ago,https://bikroy.com/shaheb-bazar/mobile-phones/...,3,2026-08-27T07:27:46.583071+00:00,individual,"iPhone 16 Pro Max, 256 GB, 96% battery health,..."
2,Samsung Galaxy A36 128 GB White,26499,Used,"Chattogram, Agrabad",2 hours ago,https://bikroy.com/agrabad/mobile-phones/samsu...,3,2026-08-27T07:27:49.338079+00:00,individual,Samsung A36\nSuper Flagship Device\nRAM 8+128\...
3,Samsung Galaxy Note 20 Ultra 256 GB Gold,20000,Used,"Rajshahi, Bagmara",05/08,https://bikroy.com/bagmara/mobile-phones/samsu...,3,2026-08-27T07:27:50.548800+00:00,individual,Please read the post carefully. The display wa...
4,Xiaomi Redmi Turbo 4 Pro 256 GB Black,37500,Used,"Dhaka, Savar",10/08,https://bikroy.com/savar/mobile-phones/xiaomi-...,5,2026-08-27T07:27:52.293699+00:00,individual,Assalamu Alaikum. I want to sell my used Redmi...

In [20]:
df.shape

(581, 10)

In [6]:
df.tail()

,raw_title,price,condition_raw,location,posted_date,url,photo_count,scraped_at,seller_type,description
547,New Xiaomi Redmi Note 14 Pro 256 GB,20000,Brand New,"Chattogram, Patenga",21/08,https://bikroy.com/patenga/mobile-phones/new-x...,3,2026-08-25T14:51:14.153267+00:00,individual,"No problem in the mobile, selling it for money"
548,Xiaomi Poco X6 Pro 256 GB Black,24500,Used,"Chattogram, Muradpur",8 hours ago,https://bikroy.com/muradpur/mobile-phones/xiao...,3,2026-08-25T14:51:14.443802+00:00,individual,Poco X6 Pro 5G\n 8GB RAM / 256GB Storage\n Ful...
549,Xiaomi Redmi Note 13 Pro+ 256 GB,26000,Used,"Chattogram, Hathazari",20/08,https://bikroy.com/hathazari/mobile-phones/xia...,5,2026-08-25T14:51:15.177522+00:00,individual,The phone is in completely fresh condition.\nL...
550,New Xiaomi Redmi Note 13 Pro 512 GB White,28999,Brand New,"Chattogram, Agrabad",12 hours ago,https://bikroy.com/agrabad/mobile-phones/new-x...,2,2026-08-25T14:51:15.603738+00:00,individual,Call or message us on WhatsApp at our number p...
551,New Xiaomi 15 Pro 256 GB Black,32000,Brand New,"Chattogram, Mirsharai",19/08,https://bikroy.com/mirsharai/mobile-phones/new...,4,2026-08-25T14:51:16.162964+00:00,individual,Brought from Dubai. Never used.

In [12]:
df.shape

(562, 10)